// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceAuthRsp.proto

package com.taoyiyi.chat.proto;

public final class DeviceAuthRsp {
  private DeviceAuthRsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceAuthRspMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.taoyiyi.chat.proto.DeviceAuthRspMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *授权成功后颁发给客户端的accesstoken
     * </pre>
     *
     * <code>string AccessToken = 1;</code>
     * @return The accessToken.
     */
    String getAccessToken();
    /**
     * <pre>
     *授权成功后颁发给客户端的accesstoken
     * </pre>
     *
     * <code>string AccessToken = 1;</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
     * @return Whether the extra field is set.
     */
    boolean hasExtra();
    /**
     * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
     * @return The extra.
     */
    DeviceAuthRspMessage.ExtraMessage getExtra();
    /**
     * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
     */
    DeviceAuthRspMessage.ExtraMessageOrBuilder getExtraOrBuilder();
  }
  /**
   * Protobuf type {@code com.taoyiyi.chat.proto.DeviceAuthRspMessage}
   */
  public static final class DeviceAuthRspMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.taoyiyi.chat.proto.DeviceAuthRspMessage)
      DeviceAuthRspMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceAuthRspMessage.newBuilder() to construct.
    private DeviceAuthRspMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceAuthRspMessage() {
      accessToken_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeviceAuthRspMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceAuthRspMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            case 18: {
              ExtraMessage.Builder subBuilder = null;
              if (extra_ != null) {
                subBuilder = extra_.toBuilder();
              }
              extra_ = input.readMessage(ExtraMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(extra_);
                extra_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeviceAuthRspMessage.class, Builder.class);
    }

    public interface ExtraMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 SupplierId = 1;</code>
       * @return The supplierId.
       */
      long getSupplierId();

      /**
       * <code>string UnionId = 2;</code>
       * @return The unionId.
       */
      String getUnionId();
      /**
       * <code>string UnionId = 2;</code>
       * @return The bytes for unionId.
       */
      com.google.protobuf.ByteString
          getUnionIdBytes();

      /**
       * <code>string SupplierName = 4;</code>
       * @return The supplierName.
       */
      String getSupplierName();
      /**
       * <code>string SupplierName = 4;</code>
       * @return The bytes for supplierName.
       */
      com.google.protobuf.ByteString
          getSupplierNameBytes();

      /**
       * <code>string NickName = 5;</code>
       * @return The nickName.
       */
      String getNickName();
      /**
       * <code>string NickName = 5;</code>
       * @return The bytes for nickName.
       */
      com.google.protobuf.ByteString
          getNickNameBytes();

      /**
       * <pre>
       * 访问www使用
       * </pre>
       *
       * <code>string Token = 6;</code>
       * @return The token.
       */
      String getToken();
      /**
       * <pre>
       * 访问www使用
       * </pre>
       *
       * <code>string Token = 6;</code>
       * @return The bytes for token.
       */
      com.google.protobuf.ByteString
          getTokenBytes();
    }
    /**
     * <pre>
     * 扩展信息
     * </pre>
     *
     * Protobuf type {@code com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage}
     */
    public static final class ExtraMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage)
        ExtraMessageOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ExtraMessage.newBuilder() to construct.
      private ExtraMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ExtraMessage() {
        unionId_ = "";
        supplierName_ = "";
        nickName_ = "";
        token_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new ExtraMessage();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ExtraMessage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                supplierId_ = input.readInt64();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                unionId_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                supplierName_ = s;
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                nickName_ = s;
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                token_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ExtraMessage.class, Builder.class);
      }

      public static final int SUPPLIERID_FIELD_NUMBER = 1;
      private long supplierId_;
      /**
       * <code>int64 SupplierId = 1;</code>
       * @return The supplierId.
       */
      @Override
      public long getSupplierId() {
        return supplierId_;
      }

      public static final int UNIONID_FIELD_NUMBER = 2;
      private volatile Object unionId_;
      /**
       * <code>string UnionId = 2;</code>
       * @return The unionId.
       */
      @Override
      public String getUnionId() {
        Object ref = unionId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          unionId_ = s;
          return s;
        }
      }
      /**
       * <code>string UnionId = 2;</code>
       * @return The bytes for unionId.
       */
      @Override
      public com.google.protobuf.ByteString
          getUnionIdBytes() {
        Object ref = unionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          unionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SUPPLIERNAME_FIELD_NUMBER = 4;
      private volatile Object supplierName_;
      /**
       * <code>string SupplierName = 4;</code>
       * @return The supplierName.
       */
      @Override
      public String getSupplierName() {
        Object ref = supplierName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          supplierName_ = s;
          return s;
        }
      }
      /**
       * <code>string SupplierName = 4;</code>
       * @return The bytes for supplierName.
       */
      @Override
      public com.google.protobuf.ByteString
          getSupplierNameBytes() {
        Object ref = supplierName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          supplierName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NICKNAME_FIELD_NUMBER = 5;
      private volatile Object nickName_;
      /**
       * <code>string NickName = 5;</code>
       * @return The nickName.
       */
      @Override
      public String getNickName() {
        Object ref = nickName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        }
      }
      /**
       * <code>string NickName = 5;</code>
       * @return The bytes for nickName.
       */
      @Override
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TOKEN_FIELD_NUMBER = 6;
      private volatile Object token_;
      /**
       * <pre>
       * 访问www使用
       * </pre>
       *
       * <code>string Token = 6;</code>
       * @return The token.
       */
      @Override
      public String getToken() {
        Object ref = token_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 访问www使用
       * </pre>
       *
       * <code>string Token = 6;</code>
       * @return The bytes for token.
       */
      @Override
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (supplierId_ != 0L) {
          output.writeInt64(1, supplierId_);
        }
        if (!getUnionIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, unionId_);
        }
        if (!getSupplierNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, supplierName_);
        }
        if (!getNickNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nickName_);
        }
        if (!getTokenBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 6, token_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (supplierId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, supplierId_);
        }
        if (!getUnionIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, unionId_);
        }
        if (!getSupplierNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, supplierName_);
        }
        if (!getNickNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nickName_);
        }
        if (!getTokenBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, token_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ExtraMessage)) {
          return super.equals(obj);
        }
        ExtraMessage other = (ExtraMessage) obj;

        if (getSupplierId()
            != other.getSupplierId()) return false;
        if (!getUnionId()
            .equals(other.getUnionId())) return false;
        if (!getSupplierName()
            .equals(other.getSupplierName())) return false;
        if (!getNickName()
            .equals(other.getNickName())) return false;
        if (!getToken()
            .equals(other.getToken())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SUPPLIERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSupplierId());
        hash = (37 * hash) + UNIONID_FIELD_NUMBER;
        hash = (53 * hash) + getUnionId().hashCode();
        hash = (37 * hash) + SUPPLIERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getSupplierName().hashCode();
        hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
        hash = (53 * hash) + getNickName().hashCode();
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ExtraMessage parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ExtraMessage parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ExtraMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ExtraMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ExtraMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ExtraMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ExtraMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ExtraMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ExtraMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ExtraMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ExtraMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ExtraMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ExtraMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * 扩展信息
       * </pre>
       *
       * Protobuf type {@code com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage)
          ExtraMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ExtraMessage.class, Builder.class);
        }

        // Construct using com.taoyiyi.chat.proto.DeviceAuthRsp.DeviceAuthRspMessage.ExtraMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          supplierId_ = 0L;

          unionId_ = "";

          supplierName_ = "";

          nickName_ = "";

          token_ = "";

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_descriptor;
        }

        @Override
        public ExtraMessage getDefaultInstanceForType() {
          return ExtraMessage.getDefaultInstance();
        }

        @Override
        public ExtraMessage build() {
          ExtraMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public ExtraMessage buildPartial() {
          ExtraMessage result = new ExtraMessage(this);
          result.supplierId_ = supplierId_;
          result.unionId_ = unionId_;
          result.supplierName_ = supplierName_;
          result.nickName_ = nickName_;
          result.token_ = token_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ExtraMessage) {
            return mergeFrom((ExtraMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ExtraMessage other) {
          if (other == ExtraMessage.getDefaultInstance()) return this;
          if (other.getSupplierId() != 0L) {
            setSupplierId(other.getSupplierId());
          }
          if (!other.getUnionId().isEmpty()) {
            unionId_ = other.unionId_;
            onChanged();
          }
          if (!other.getSupplierName().isEmpty()) {
            supplierName_ = other.supplierName_;
            onChanged();
          }
          if (!other.getNickName().isEmpty()) {
            nickName_ = other.nickName_;
            onChanged();
          }
          if (!other.getToken().isEmpty()) {
            token_ = other.token_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ExtraMessage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ExtraMessage) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long supplierId_ ;
        /**
         * <code>int64 SupplierId = 1;</code>
         * @return The supplierId.
         */
        @Override
        public long getSupplierId() {
          return supplierId_;
        }
        /**
         * <code>int64 SupplierId = 1;</code>
         * @param value The supplierId to set.
         * @return This builder for chaining.
         */
        public Builder setSupplierId(long value) {
          
          supplierId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 SupplierId = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearSupplierId() {
          
          supplierId_ = 0L;
          onChanged();
          return this;
        }

        private Object unionId_ = "";
        /**
         * <code>string UnionId = 2;</code>
         * @return The unionId.
         */
        public String getUnionId() {
          Object ref = unionId_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            unionId_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string UnionId = 2;</code>
         * @return The bytes for unionId.
         */
        public com.google.protobuf.ByteString
            getUnionIdBytes() {
          Object ref = unionId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            unionId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string UnionId = 2;</code>
         * @param value The unionId to set.
         * @return This builder for chaining.
         */
        public Builder setUnionId(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          unionId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string UnionId = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearUnionId() {
          
          unionId_ = getDefaultInstance().getUnionId();
          onChanged();
          return this;
        }
        /**
         * <code>string UnionId = 2;</code>
         * @param value The bytes for unionId to set.
         * @return This builder for chaining.
         */
        public Builder setUnionIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          unionId_ = value;
          onChanged();
          return this;
        }

        private Object supplierName_ = "";
        /**
         * <code>string SupplierName = 4;</code>
         * @return The supplierName.
         */
        public String getSupplierName() {
          Object ref = supplierName_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            supplierName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string SupplierName = 4;</code>
         * @return The bytes for supplierName.
         */
        public com.google.protobuf.ByteString
            getSupplierNameBytes() {
          Object ref = supplierName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            supplierName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string SupplierName = 4;</code>
         * @param value The supplierName to set.
         * @return This builder for chaining.
         */
        public Builder setSupplierName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          supplierName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string SupplierName = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearSupplierName() {
          
          supplierName_ = getDefaultInstance().getSupplierName();
          onChanged();
          return this;
        }
        /**
         * <code>string SupplierName = 4;</code>
         * @param value The bytes for supplierName to set.
         * @return This builder for chaining.
         */
        public Builder setSupplierNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          supplierName_ = value;
          onChanged();
          return this;
        }

        private Object nickName_ = "";
        /**
         * <code>string NickName = 5;</code>
         * @return The nickName.
         */
        public String getNickName() {
          Object ref = nickName_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            nickName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string NickName = 5;</code>
         * @return The bytes for nickName.
         */
        public com.google.protobuf.ByteString
            getNickNameBytes() {
          Object ref = nickName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            nickName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string NickName = 5;</code>
         * @param value The nickName to set.
         * @return This builder for chaining.
         */
        public Builder setNickName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          nickName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string NickName = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearNickName() {
          
          nickName_ = getDefaultInstance().getNickName();
          onChanged();
          return this;
        }
        /**
         * <code>string NickName = 5;</code>
         * @param value The bytes for nickName to set.
         * @return This builder for chaining.
         */
        public Builder setNickNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          nickName_ = value;
          onChanged();
          return this;
        }

        private Object token_ = "";
        /**
         * <pre>
         * 访问www使用
         * </pre>
         *
         * <code>string Token = 6;</code>
         * @return The token.
         */
        public String getToken() {
          Object ref = token_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            token_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 访问www使用
         * </pre>
         *
         * <code>string Token = 6;</code>
         * @return The bytes for token.
         */
        public com.google.protobuf.ByteString
            getTokenBytes() {
          Object ref = token_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            token_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 访问www使用
         * </pre>
         *
         * <code>string Token = 6;</code>
         * @param value The token to set.
         * @return This builder for chaining.
         */
        public Builder setToken(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          token_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 访问www使用
         * </pre>
         *
         * <code>string Token = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearToken() {
          
          token_ = getDefaultInstance().getToken();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 访问www使用
         * </pre>
         *
         * <code>string Token = 6;</code>
         * @param value The bytes for token to set.
         * @return This builder for chaining.
         */
        public Builder setTokenBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          token_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage)
      }

      // @@protoc_insertion_point(class_scope:com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage)
      private static final ExtraMessage DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ExtraMessage();
      }

      public static ExtraMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ExtraMessage>
          PARSER = new com.google.protobuf.AbstractParser<ExtraMessage>() {
        @Override
        public ExtraMessage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ExtraMessage(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ExtraMessage> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<ExtraMessage> getParserForType() {
        return PARSER;
      }

      @Override
      public ExtraMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 1;
    private volatile Object accessToken_;
    /**
     * <pre>
     *授权成功后颁发给客户端的accesstoken
     * </pre>
     *
     * <code>string AccessToken = 1;</code>
     * @return The accessToken.
     */
    @Override
    public String getAccessToken() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *授权成功后颁发给客户端的accesstoken
     * </pre>
     *
     * <code>string AccessToken = 1;</code>
     * @return The bytes for accessToken.
     */
    @Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_FIELD_NUMBER = 2;
    private ExtraMessage extra_;
    /**
     * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
     * @return Whether the extra field is set.
     */
    @Override
    public boolean hasExtra() {
      return extra_ != null;
    }
    /**
     * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
     * @return The extra.
     */
    @Override
    public ExtraMessage getExtra() {
      return extra_ == null ? ExtraMessage.getDefaultInstance() : extra_;
    }
    /**
     * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
     */
    @Override
    public ExtraMessageOrBuilder getExtraOrBuilder() {
      return getExtra();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
      }
      if (extra_ != null) {
        output.writeMessage(2, getExtra());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
      }
      if (extra_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getExtra());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DeviceAuthRspMessage)) {
        return super.equals(obj);
      }
      DeviceAuthRspMessage other = (DeviceAuthRspMessage) obj;

      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
      if (hasExtra() != other.hasExtra()) return false;
      if (hasExtra()) {
        if (!getExtra()
            .equals(other.getExtra())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      if (hasExtra()) {
        hash = (37 * hash) + EXTRA_FIELD_NUMBER;
        hash = (53 * hash) + getExtra().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DeviceAuthRspMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceAuthRspMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceAuthRspMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceAuthRspMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceAuthRspMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceAuthRspMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceAuthRspMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DeviceAuthRspMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DeviceAuthRspMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DeviceAuthRspMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DeviceAuthRspMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DeviceAuthRspMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DeviceAuthRspMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoyiyi.chat.proto.DeviceAuthRspMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.taoyiyi.chat.proto.DeviceAuthRspMessage)
        DeviceAuthRspMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeviceAuthRspMessage.class, Builder.class);
      }

      // Construct using com.taoyiyi.chat.proto.DeviceAuthRsp.DeviceAuthRspMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        accessToken_ = "";

        if (extraBuilder_ == null) {
          extra_ = null;
        } else {
          extra_ = null;
          extraBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DeviceAuthRsp.internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_descriptor;
      }

      @Override
      public DeviceAuthRspMessage getDefaultInstanceForType() {
        return DeviceAuthRspMessage.getDefaultInstance();
      }

      @Override
      public DeviceAuthRspMessage build() {
        DeviceAuthRspMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DeviceAuthRspMessage buildPartial() {
        DeviceAuthRspMessage result = new DeviceAuthRspMessage(this);
        result.accessToken_ = accessToken_;
        if (extraBuilder_ == null) {
          result.extra_ = extra_;
        } else {
          result.extra_ = extraBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeviceAuthRspMessage) {
          return mergeFrom((DeviceAuthRspMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeviceAuthRspMessage other) {
        if (other == DeviceAuthRspMessage.getDefaultInstance()) return this;
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (other.hasExtra()) {
          mergeExtra(other.getExtra());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeviceAuthRspMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeviceAuthRspMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object accessToken_ = "";
      /**
       * <pre>
       *授权成功后颁发给客户端的accesstoken
       * </pre>
       *
       * <code>string AccessToken = 1;</code>
       * @return The accessToken.
       */
      public String getAccessToken() {
        Object ref = accessToken_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *授权成功后颁发给客户端的accesstoken
       * </pre>
       *
       * <code>string AccessToken = 1;</code>
       * @return The bytes for accessToken.
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *授权成功后颁发给客户端的accesstoken
       * </pre>
       *
       * <code>string AccessToken = 1;</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *授权成功后颁发给客户端的accesstoken
       * </pre>
       *
       * <code>string AccessToken = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *授权成功后颁发给客户端的accesstoken
       * </pre>
       *
       * <code>string AccessToken = 1;</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }

      private ExtraMessage extra_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ExtraMessage, ExtraMessage.Builder, ExtraMessageOrBuilder> extraBuilder_;
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       * @return Whether the extra field is set.
       */
      public boolean hasExtra() {
        return extraBuilder_ != null || extra_ != null;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       * @return The extra.
       */
      public ExtraMessage getExtra() {
        if (extraBuilder_ == null) {
          return extra_ == null ? ExtraMessage.getDefaultInstance() : extra_;
        } else {
          return extraBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       */
      public Builder setExtra(ExtraMessage value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          extra_ = value;
          onChanged();
        } else {
          extraBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       */
      public Builder setExtra(
          ExtraMessage.Builder builderForValue) {
        if (extraBuilder_ == null) {
          extra_ = builderForValue.build();
          onChanged();
        } else {
          extraBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       */
      public Builder mergeExtra(ExtraMessage value) {
        if (extraBuilder_ == null) {
          if (extra_ != null) {
            extra_ =
              ExtraMessage.newBuilder(extra_).mergeFrom(value).buildPartial();
          } else {
            extra_ = value;
          }
          onChanged();
        } else {
          extraBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       */
      public Builder clearExtra() {
        if (extraBuilder_ == null) {
          extra_ = null;
          onChanged();
        } else {
          extra_ = null;
          extraBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       */
      public ExtraMessage.Builder getExtraBuilder() {
        
        onChanged();
        return getExtraFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       */
      public ExtraMessageOrBuilder getExtraOrBuilder() {
        if (extraBuilder_ != null) {
          return extraBuilder_.getMessageOrBuilder();
        } else {
          return extra_ == null ?
              ExtraMessage.getDefaultInstance() : extra_;
        }
      }
      /**
       * <code>.com.taoyiyi.chat.proto.DeviceAuthRspMessage.ExtraMessage Extra = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ExtraMessage, ExtraMessage.Builder, ExtraMessageOrBuilder>
          getExtraFieldBuilder() {
        if (extraBuilder_ == null) {
          extraBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ExtraMessage, ExtraMessage.Builder, ExtraMessageOrBuilder>(
                  getExtra(),
                  getParentForChildren(),
                  isClean());
          extra_ = null;
        }
        return extraBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.taoyiyi.chat.proto.DeviceAuthRspMessage)
    }

    // @@protoc_insertion_point(class_scope:com.taoyiyi.chat.proto.DeviceAuthRspMessage)
    private static final DeviceAuthRspMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DeviceAuthRspMessage();
    }

    public static DeviceAuthRspMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceAuthRspMessage>
        PARSER = new com.google.protobuf.AbstractParser<DeviceAuthRspMessage>() {
      @Override
      public DeviceAuthRspMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceAuthRspMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceAuthRspMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DeviceAuthRspMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public DeviceAuthRspMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023DeviceAuthRsp.proto\022\026com.taoyiyi.chat." +
      "proto\032\026TransportMessage.proto\"\341\001\n\024Device" +
      "AuthRspMessage\022\023\n\013AccessToken\030\001 \001(\t\022H\n\005E" +
      "xtra\030\002 \001(\01329.com.taoyiyi.chat.proto.Devi" +
      "ceAuthRspMessage.ExtraMessage\032j\n\014ExtraMe" +
      "ssage\022\022\n\nSupplierId\030\001 \001(\003\022\017\n\007UnionId\030\002 \001" +
      "(\t\022\024\n\014SupplierName\030\004 \001(\t\022\020\n\010NickName\030\005 \001" +
      "(\t\022\r\n\005Token\030\006 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TransportMessageOuterClass.getDescriptor(),
        });
    internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_descriptor,
        new String[] { "AccessToken", "Extra", });
    internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_descriptor =
      internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_descriptor.getNestedTypes().get(0);
    internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_taoyiyi_chat_proto_DeviceAuthRspMessage_ExtraMessage_descriptor,
        new String[] { "SupplierId", "UnionId", "SupplierName", "NickName", "Token", });
    TransportMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
