// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorMessage.proto

package com.taoyiyi.chat.proto;

public final class ErrorMessageOuterClass {
  private ErrorMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ErrorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.taoyiyi.chat.proto.ErrorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *错误码（只在响应类消息时需要赋值)
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    int getErrorCodeValue();
    /**
     * <pre>
     *错误码（只在响应类消息时需要赋值)
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
     * @return The errorCode.
     */
    TransportMessageOuterClass.EnumErrorCode getErrorCode();

    /**
     * <pre>
     *错误信息（只在响应类消息时需要赋值）
     * </pre>
     *
     * <code>string ErrorMsg = 2;</code>
     * @return The errorMsg.
     */
    String getErrorMsg();
    /**
     * <pre>
     *错误信息（只在响应类消息时需要赋值）
     * </pre>
     *
     * <code>string ErrorMsg = 2;</code>
     * @return The bytes for errorMsg.
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();
  }
  /**
   * Protobuf type {@code com.taoyiyi.chat.proto.ErrorMessage}
   */
  public static final class ErrorMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.taoyiyi.chat.proto.ErrorMessage)
      ErrorMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ErrorMessage.newBuilder() to construct.
    private ErrorMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorMessage() {
      errorCode_ = 0;
      errorMsg_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ErrorMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              errorCode_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              errorMsg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ErrorMessageOuterClass.internal_static_com_taoyiyi_chat_proto_ErrorMessage_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ErrorMessageOuterClass.internal_static_com_taoyiyi_chat_proto_ErrorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ErrorMessage.class, Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <pre>
     *错误码（只在响应类消息时需要赋值)
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    @Override public int getErrorCodeValue() {
      return errorCode_;
    }
    /**
     * <pre>
     *错误码（只在响应类消息时需要赋值)
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
     * @return The errorCode.
     */
    @Override public TransportMessageOuterClass.EnumErrorCode getErrorCode() {
      @SuppressWarnings("deprecation")
      TransportMessageOuterClass.EnumErrorCode result = TransportMessageOuterClass.EnumErrorCode.valueOf(errorCode_);
      return result == null ? TransportMessageOuterClass.EnumErrorCode.UNRECOGNIZED : result;
    }

    public static final int ERRORMSG_FIELD_NUMBER = 2;
    private volatile Object errorMsg_;
    /**
     * <pre>
     *错误信息（只在响应类消息时需要赋值）
     * </pre>
     *
     * <code>string ErrorMsg = 2;</code>
     * @return The errorMsg.
     */
    @Override
    public String getErrorMsg() {
      Object ref = errorMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *错误信息（只在响应类消息时需要赋值）
     * </pre>
     *
     * <code>string ErrorMsg = 2;</code>
     * @return The bytes for errorMsg.
     */
    @Override
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != TransportMessageOuterClass.EnumErrorCode.Success.getNumber()) {
        output.writeEnum(1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMsg_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != TransportMessageOuterClass.EnumErrorCode.Success.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ErrorMessage)) {
        return super.equals(obj);
      }
      ErrorMessage other = (ErrorMessage) obj;

      if (errorCode_ != other.errorCode_) return false;
      if (!getErrorMsg()
          .equals(other.getErrorMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + errorCode_;
      hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ErrorMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ErrorMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ErrorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ErrorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ErrorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ErrorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ErrorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ErrorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ErrorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ErrorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ErrorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoyiyi.chat.proto.ErrorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.taoyiyi.chat.proto.ErrorMessage)
        ErrorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ErrorMessageOuterClass.internal_static_com_taoyiyi_chat_proto_ErrorMessage_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ErrorMessageOuterClass.internal_static_com_taoyiyi_chat_proto_ErrorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ErrorMessage.class, Builder.class);
      }

      // Construct using com.taoyiyi.chat.proto.ErrorMessageOuterClass.ErrorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        errorMsg_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ErrorMessageOuterClass.internal_static_com_taoyiyi_chat_proto_ErrorMessage_descriptor;
      }

      @Override
      public ErrorMessage getDefaultInstanceForType() {
        return ErrorMessage.getDefaultInstance();
      }

      @Override
      public ErrorMessage build() {
        ErrorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ErrorMessage buildPartial() {
        ErrorMessage result = new ErrorMessage(this);
        result.errorCode_ = errorCode_;
        result.errorMsg_ = errorMsg_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ErrorMessage) {
          return mergeFrom((ErrorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ErrorMessage other) {
        if (other == ErrorMessage.getDefaultInstance()) return this;
        if (other.errorCode_ != 0) {
          setErrorCodeValue(other.getErrorCodeValue());
        }
        if (!other.getErrorMsg().isEmpty()) {
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ErrorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ErrorMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ = 0;
      /**
       * <pre>
       *错误码（只在响应类消息时需要赋值)
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
       * @return The enum numeric value on the wire for errorCode.
       */
      @Override public int getErrorCodeValue() {
        return errorCode_;
      }
      /**
       * <pre>
       *错误码（只在响应类消息时需要赋值)
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
       * @param value The enum numeric value on the wire for errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCodeValue(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误码（只在响应类消息时需要赋值)
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
       * @return The errorCode.
       */
      @Override
      public TransportMessageOuterClass.EnumErrorCode getErrorCode() {
        @SuppressWarnings("deprecation")
        TransportMessageOuterClass.EnumErrorCode result = TransportMessageOuterClass.EnumErrorCode.valueOf(errorCode_);
        return result == null ? TransportMessageOuterClass.EnumErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *错误码（只在响应类消息时需要赋值)
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(TransportMessageOuterClass.EnumErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        errorCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误码（只在响应类消息时需要赋值)
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumErrorCode ErrorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private Object errorMsg_ = "";
      /**
       * <pre>
       *错误信息（只在响应类消息时需要赋值）
       * </pre>
       *
       * <code>string ErrorMsg = 2;</code>
       * @return The errorMsg.
       */
      public String getErrorMsg() {
        Object ref = errorMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *错误信息（只在响应类消息时需要赋值）
       * </pre>
       *
       * <code>string ErrorMsg = 2;</code>
       * @return The bytes for errorMsg.
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误信息（只在响应类消息时需要赋值）
       * </pre>
       *
       * <code>string ErrorMsg = 2;</code>
       * @param value The errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息（只在响应类消息时需要赋值）
       * </pre>
       *
       * <code>string ErrorMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMsg() {
        
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息（只在响应类消息时需要赋值）
       * </pre>
       *
       * <code>string ErrorMsg = 2;</code>
       * @param value The bytes for errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMsg_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.taoyiyi.chat.proto.ErrorMessage)
    }

    // @@protoc_insertion_point(class_scope:com.taoyiyi.chat.proto.ErrorMessage)
    private static final ErrorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ErrorMessage();
    }

    public static ErrorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorMessage>
        PARSER = new com.google.protobuf.AbstractParser<ErrorMessage>() {
      @Override
      public ErrorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ErrorMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public ErrorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoyiyi_chat_proto_ErrorMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_taoyiyi_chat_proto_ErrorMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022ErrorMessage.proto\022\026com.taoyiyi.chat.p" +
      "roto\032\026TransportMessage.proto\"Z\n\014ErrorMes" +
      "sage\0228\n\tErrorCode\030\001 \001(\0162%.com.taoyiyi.ch" +
      "at.proto.EnumErrorCode\022\020\n\010ErrorMsg\030\002 \001(\t" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TransportMessageOuterClass.getDescriptor(),
        });
    internal_static_com_taoyiyi_chat_proto_ErrorMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_taoyiyi_chat_proto_ErrorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_taoyiyi_chat_proto_ErrorMessage_descriptor,
        new String[] { "ErrorCode", "ErrorMsg", });
    TransportMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
